---
- name: Converge
  hosts: all
  roles:
    # NOTE: runs using default role variables
    - role: genlab.ansible_borgbecue
      config: "config.yaml"
      repo: https://github.com/corvus-migratorius/borgbecue.git
      timer_oncalendar: '*-*-* 00:00:00'
      repo_keyscan_val: >
        "|1|OqrkyKRtYyeWS5zCyoYMSCcTdvU=|oI/SzOW5FC0wu3G3i8x5rwtOeS8= ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIA6JhHdm9I7xksW2ZWdmvU4XsHxQX9m4KeTMGY4tFWao"
