---
- name: Verify
  hosts: all
  gather_facts: false
  any_errors_fatal: true

  tasks:
    # https://github.com/ansible/molecule/issues/3587#issuecomment-1158650179
    - name: "Include default vars"
      ansible.builtin.include_vars:
        dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/"
        extensions: [ 'yml' ]

    - name: "Run borgbecue"
      changed_when: false
      register: test_version_installed
      ansible.builtin.command:
        cmd: "borgbecue --version"

    - name: "Assert that the requested version is already installed"
      ansible.builtin.assert:
        that: "version in test_version_installed.stdout"
        success_msg: "expected version available ({{ test_version_installed.stdout }})"
        fail_msg: "expected version: {{ version }}, actual: {{ test_version_installed.stdout }}"
